name: Reusable Build, Push, and Deploy

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      artifact-registry-repo:
        required: true
        type: string
      gitops-repo:
        required: true
        type: string
      environment:
        required: true
        type: string # e.g., dev
    secrets:
      GCP_SA_KEY:
        required: true
      GITOPS_PAT:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.version }}
      sha: ${{ steps.vars.outputs.sha }}
    steps:
      - name: Checkout Application Code
        uses: actions/checkout@v3

      - name: Extract Artifact Registry hostname
        id: ar-host
        run: echo "host=$(echo ${{ inputs.artifact-registry-repo }} | cut -d'/' -f1)" >> $GITHUB_OUTPUT

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ steps.ar-host.outputs.host }}
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Get Version and Git SHA
        id: vars
        run: |
          echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image to Artifact Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ inputs.artifact-registry-repo }}/${{ inputs.image-name }}:${{ steps.vars.outputs.sha }}
            ${{ inputs.artifact-registry-repo }}/${{ inputs.image-name }}:${{ steps.vars.outputs.version }}

  update-gitops:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.gitops-repo }}
          token: ${{ secrets.GITOPS_PAT }}
          path: gitops

      - name: Update image tag in properties file
        run: |
          PROPERTIES_FILE="gitops/environments/${{ inputs.environment }}/image_tags.properties"
          if [ ! -f "$PROPERTIES_FILE" ]; then
            echo "Error: Properties file not found at $PROPERTIES_FILE"
            exit 1
          fi
          # Use sed to find and replace the image tag for the specific application
          sed -i "s|^\(${{ inputs.image-name }}.image.tag=\).*|\1${{ needs.build-and-push.outputs.tag }}|" "$PROPERTIES_FILE"

      - name: Commit and push changes
        run: |
          cd gitops
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "Update ${{ inputs.image-name }} image tag to ${{ needs.build-and-push.outputs.tag }} for ${{ inputs.environment }} env"
          git push